name: Build Repo
on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone self
        run: git clone --depth 1 https://github.com/${{ github.repository }}.git kit
      - name: Clone repo
        run: git clone --depth 1 ${{ inputs.repo_url }}
      - name: Build package
        run: |
          cd $(basename ${{ inputs.url }} .git)
          chmod u+x ../kit/check-build-simple
          ../kit/check-build-simple
