name: Check no-subscription
on:
  workflow_dispatch:

jobs:
  no-subscription:
    uses: ./.github/workflows/check-simple.yaml
    with:
      url: https://github.com/free-pmx/free-pmx-no-subscription.git
      ref: main