name: Check no-subscription
on:
  workflow_dispatch:

jobs:
  no-subscription:
    uses: disputechalice/test-repro-runner/.github/workflows/check-simple.yaml@main
    with:
      url: https://github.com/free-pmx/free-pmx-no-subscription.git
      ref: main